-- 코드를 입력하세요
SELECT A.CAR_ID, 
       A.CAR_TYPE,
       A.DAILY_FEE*(1-C.DISCOUNT_RATE/100)*30 AS FEE
FROM  CAR_RENTAL_COMPANY_CAR A
    INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
        ON A.CAR_TYPE=C.CAR_TYPE
    WHERE
        C.CAR_TYPE IN ('세단', 'SUV')  
        AND C.DURATION_TYPE='30일 이상'
        AND A.CAR_ID NOT IN(
            SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE START_DATE<='2022-11-30'AND END_DATE>='2022-11-01'
        )
        
HAVING FEE>=500000 AND FEE<2000000  
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC;
