-- 코드를 작성해주세요
WITH RANKED AS (
    SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS Q
    FROM ECOLI_DATA 
)
SELECT ID, 
CASE Q
WHEN 1 THEN 'CRITICAL'
WHEN 2 THEN 'HIGH'
WHEN 3 THEN 'MEDIUM'
WHEN 4 THEN 'LOW'
END AS COLONY_NAME
FROM RANKED
ORDER BY ID ASC;