-- 코드를 입력하세요
SELECT YEAR(S.SALES_DATE)AS YEAR,  
MONTH(S.SALES_DATE)AS MONTH, 
COUNT(DISTINCT(S.USER_ID))AS PURCHASED_USERS, 

ROUND(COUNT(DISTINCT U.USER_ID) /
(SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE JOINED>='2021-01-01' AND JOINED<='2021-12-31'),1)
AS PUCHASED_RATIO 

FROM USER_INFO U
INNER JOIN
ONLINE_SALE S
ON U.USER_ID=S.USER_ID
WHERE U.JOINED>='2021-01-01' AND U.JOINED<='2021-12-31'
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC;